fix pre commit script

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,3 +1,49 @@
-isort --diff -c $(git status -s | grep -E '\.py$' | cut -c 4-)
-black mesada tests
-flake8 $(git status -s | grep -E '\.py$' | cut -c 4-)
+
+set +e
+
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+RESET='\033[0m'
+
+function no_log_if_successful {
+    set +e
+    COMMAND=$@
+    printf "Running $COMMAND ... "
+
+    OUTPUT=$($@ 2>&1)
+    EXIT_CODE=$?
+    if [[ $EXIT_CODE -gt 0 ]]; then
+        printf "${RED}Failed${RESET} 😢\n"
+        printf "%s\n\n" "${OUTPUT}"
+    else
+        printf "${GREEN}Success!${RESET}\n"
+    fi
+    set -e
+    return $EXIT_CODE
+}
+
+
+SOURCE=$(basename "${BASH_SOURCE[0]}")
+SOURCE_DIR=$(dirname "${BASH_SOURCE[0]}")
+
+
+BASE_BRANCH="origin/dev"
+echo ""
+
+MODIFIED_PY_FILES=$(git status -s | grep -E '\.py$' | cut -c 4-)
+
+if [[ $MODIFIED_PY_FILES != "" ]]; then
+    echo $MODIFIED_PY_FILES | no_log_if_successful xargs flake8
+    set +e
+else
+    printf "Running flake8 ... ${GREEN}Ignored!${RESET} (no *.py files with changes)\n"
+fi
+
+if [[ $MODIFIED_PY_FILES != "" ]]; then
+    echo $MODIFIED_PY_FILES | no_log_if_successful isort 
+    set +e
+else
+    printf "Running isort ... ${GREEN}Ignored!${RESET} (no *.py files with changes)\n"
+fi
+
+no_log_if_successful black mesada tests
